name: flask
channels:
  - defaults
dependencies:
  - attrs>=19.3.0
  - backcall>=0.1.0
  - blas>=1.0
  - ca-certificates>=2020.1.1
  - certifi>=2020.4.5.1
  - click>=7.0
  - decorator>=4.4.1
  - flask>=1.1.1
  - flask-cors>=3.0.8
  - flask-socketio>=4.2.1
  - itsdangerous>=1.1.0
  - jedi>=0.15.2
  - jinja2>=2.10.3
  - libedit>=3.1.20181209
  - libffi>=3.2.1
  - markupsafe>=1.1.1
  - ncurses>=6.1
  - numpy>=1.17.4
  - numpy-base>=1.17.4
  - openssl>=1.1.1f
  - parso>=0.5.2
  - pexpect>=4.7.0
  - pickleshare>=0.7.5
  - pip>=19.3.1
  - plotly>=4.4.1
  - prompt_toolkit>=3.0.2
  - ptyprocess>=0.6.0
  - pygments>=2.5.2
  - pymongo>=3.9.0
  - python>=3.8.1
  - python-engineio>=3.9.3
  - python-socketio>=4.3.1
  - readline>=7.0
  - retrying>=1.3.3
  - setuptools>=44.0.0
  - six>=1.13.0
  - sqlite>=3.30.1
  - tk>=8.6.8
  - traitlets>=4.3.3
  - wcwidth>=0.1.7
  - werkzeug>=0.16.0
  - wheel>=0.33.6
  - xz>=5.2.4
  - zlib>=1.2.11
  - pip:
    - alembic>=1.4.1
    - aniso8601>=8.0.0
    - cookiecutter>=1.7.0
    - coverage>=5.0.4
    - dnspython>=1.16.0
    - eventlet>=0.25.1
    - flask-migrate>=2.5.3
    - flask-restful>=0.3.7
    - flask-restplus>=0.13.0
    - flask-session>=0.3.1
    - flask-sqlalchemy>=2.4.1
    - gevent>=1.4.0
    - greenlet>=0.4.15
    - gunicorn>=20.0.4
    - jsonschema>=3.2.0
    - mako>=1.1.2
    - monotonic>=1.5
    - more-itertools>=8.2.0
    - packaging>=20.3
    - pluggy>=0.13.1
    - py>=1.8.1
    - pyparsing>=2.4.6
    - pyrsistent>=0.15.7
    - pytest>=5.4.1
    - pytest-cov>=2.8.1
    - pytest-mock>=2.0.0
    - python-editor>=1.0.4
    - pytz>=2019.3
    - sqlalchemy>=1.3.15